### ISSUE TITLE
might want to rename the repo to maxthefox9172.github.io

### ISSUE THREAD

**Issue by TorutheRedFox** [maxthefox9172/maxthefox9172.github.io#1]
any github site that differs from your username followed by ".github.io" becomes a subpage

**Comment by TorutheRedFox** [comment]
btw you can remove the ".html" from the end of each url by putting the html in a folder with its name, and renaming the file itself to index.html

**Comment by maxthefox9172** [comment]
> any github site that differs from your username followed by ".github.io" becomes a subpage

i updated the repo name now
