### ISSUE TITLE
404 on homepage (it has to be index.html)

### ISSUE THREAD

**Issue by TorutheRedFox** [maxthefox9172/maxthefox9172.github.io#2]
to get a url like maxthefox9172.github.io/neoalpha rather than maxthefox9172.github.io/neoalpha.html, put neoalpha.html in a folder called neoalpha and rename it to index.html

oh and also rename home back to index.html as the main page results in a 404, which is not a good first sight for a page, that's prolly more important

**Comment by TorutheRedFox** [comment]
eh turns out github does this anyway but there's still no true homepage

**Comment by maxthefox9172** [comment]
> to get a url like maxthefox9172.github.io/neoalpha rather than maxthefox9172.github.io/neoalpha.html, put neoalpha.html in a folder called neoalpha and rename it to index.html

i tried doing this but now i have another problem which is links in the subsites redirect incorrectly e.g. when i click home it doesnt redirect to home but it redirects me to a subsite in that subsite which doesnt exist. do you know if i gotta change these links to full links or is there a way for them to stay like this (that is e.g.: `<a href="home">Home</a>` )?

**Comment by TorutheRedFox** [comment]
a link back to home would be ``<a href="/">Home</a>``

**Comment by TorutheRedFox** [comment]
remember to denote root with the /, paths are like on unix

**Comment by TorutheRedFox** [comment]
so
``<a href="/">Home</a>``
``<a href="/neoalpha/">Neoalpha</a>``
etc.
